server:
  port: 7071
spring:
  jpa:
    show-sql: true
   # properties:
   #   hibernate:
        #dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: h02.08.1996H
    driver-class-name: com.mysql.cj.jdbc.Driver

